image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip3 install virtualenv
      python3 -m virtualenv --system-site-packages .venv
      source ./.venv/bin/activate
      pip3 install -r ./requirements.txt
